Yaml syntax

diff --git a/client-applications/.github/workflows/proc-build_branch_and_release.yml b/client-applications/.github/workflows/proc-build_branch_and_release.yml
--- a/client-applications/.github/workflows/proc-build_branch_and_release.yml
+++ b/client-applications/.github/workflows/proc-build_branch_and_release.yml
@@ -111,13 +111,13 @@ jobs:
         config:
           - os: ubuntu-latest
             artifact_name: "Linux-64bit"
-            artifact_relpath: "/desktop/release/linux/TODO"
-         - os: windows-latest
-           artifact_name: "Windows-64bit"
-           artifact_relpath: "/desktop/release/windows/TODO"
-         - os: macos-latest
-           artifact_name: "macOS-64bit"
-           artifact_relpath: "/desktop/release/mac/Fractal.app"
+            artifact_relpath: "/desktop/release/linux/Fractal"
+          - os: windows-latest
+            artifact_name: "Windows-64bit"
+            artifact_relpath: "/desktop/release/windows/Fractal.exe"
+          - os: macos-latest
+            artifact_name: "macOS-64bit"
+            artifact_relpath: "/desktop/release/mac/Fractal.app"
 
     steps:
       - name: Check out Git repository
@@ -205,3 +205,162 @@ jobs:
         run: |
           poetry run ./desktop/build_and_publish.py --set-version ${{ needs.params.outputs.version_id }}  --update-channel ${{ needs.params.outputs.update_channel }} || true
           find . -not \( -path ./desktop/node_modules -prune \) -not \( -path ./.git -prune \)
+
+
+
+  create-release:
+    name: Create release
+    needs: [params, build]
+    if: always() # See not in first step to understand why this is set to always run (which would seem incorrect since it should only run when builds succeed)
+    runs-on: ubuntu-latest
+    outputs:
+      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
+      version_id: ${{ steps.release_info.outputs.version_id }}
+    steps:
+      - name: Check if all builds succeeded
+        # This step was added because the job level if `needs.build.result == 'success' && (needs.test_client.result == 'skipped' || needs.test_client.result == 'success')`
+        # was resulting in the job skipping even when the value was shown to be true when printed.
+        run: |
+          if ! ${{ needs.params.outputs.should_release }}; then
+            echo "Killing release job because should_release=${{ needs.params.outputs.should_release }}"
+            exit 1
+          fi
+          if ${{ needs.build.result == 'success' && (needs.test_client.result == 'skipped' || needs.test_client.result == 'success') }}; then # this true/false was derived from a GHA expression
+            echo "Proceeding with job"
+          else
+            echo "Killing release job because builds or tests failed"
+            exit 1
+          fi
+      # TODO convert this into its own Github Action (ie. not embedded in this workflow but as its own published action)
+      # - https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action
+      # - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-action-in-the-same-repository-as-the-workflow
+      - name: Determine the new release version ID
+        id: release_info
+        uses: actions/github-script@v2
+        with:
+          script: |
+            if ("${{ needs.params.outputs.overridden_version_id }}") {
+              console.log(`::set-output name=version_id::${{ needs.params.outputs.overridden_version_id }}`)
+              return
+            }
+            const cur_ref_name = "${{ needs.params.outputs.ref_name }}"
+            const accumulate_paged_list = async (doReq, start_page = 0) => {
+              let aggregate = []
+              let new_list
+              do {
+                new_list = await doReq(start_page)
+                aggregate = aggregate.concat(new_list)
+                start_page++
+              } while (new_list.length > 0)
+              return aggregate
+            }
+            const releases = await accumulate_paged_list(
+              async (i) => (await github.repos.listReleases({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                per_page: 100,
+                page: i,
+              })).data,
+              1 // Github's REST API paging is 1-indexed (not 0-indexed)
+            )
+            version_regex = /(\S+)-(\d{8})\.(\d+)/
+            console.log("Found ${releases.length} releases:")
+            const relevant_releases = releases
+              .map(r => { console.log(`  ${r.name}`); return r.name.match(version_regex) })
+              .filter(m => !!m)
+              .filter(([, ref_name]) => ref_name == cur_ref_name)
+            relevant_releases.sort()
+
+            const cur_date = new Date().toISOString().split("T")[0].replace(/-/g, "") // should always be in UTC
+            let cur_date_point = 1
+            console.log(`New release is for the "${cur_ref_name}" ref on ${cur_date}`)
+
+            const latest_release = relevant_releases[relevant_releases.length - 1]
+            if (latest_release) {
+              const [full, ref_name, date, point] = latest_release
+              console.log(`Comparing against latest release relevant release: "${full}".`)
+              if (date == cur_date) {
+                cur_date_point = Number(point) + 1
+              }
+            } else {
+              console.log(`Of ${releases.length} releases found none were for the "${cur_ref_name}" ref (or at least none followed the ref_name-YYYYMMDD.# naming pattern)`)
+            }
+            version_id = `${cur_ref_name}-${cur_date}.${cur_date_point}`
+            console.log(`::set-output name=version_id::${version_id}`)
+          github-token: ${{secrets.GITHUB_TOKEN}}
+      - uses: actions/checkout@v2
+        with:
+          ref: ${{ needs.params.outputs.ref }}
+      - name: Tag HEAD as ${{ steps.release_info.outputs.version_id }} and push
+        run: |
+          git tag ${{ steps.release_info.outputs.version_id }}
+          git push origin --tags
+      - name: Create release for ${{ steps.release_info.outputs.version_id }}
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ steps.release_info.outputs.version_id }}
+          release_name: ${{ steps.release_info.outputs.version_id }}
+          body: |
+            This was an automated release produced via the *${{ github.workflow }}* workflow in Github Actions which was triggered by *${{ github.event_name }}*.
+
+            **Version ID:** `${{ steps.release_info.outputs.version_id }}`
+
+            **Commit:** `${{ needs.params.outputs.git_sha }}`
+
+            **Release parameters:**
+
+            Inputs:
+            ```json
+            ${{ toJson(github.event.inputs) }}
+            ```
+
+            Derived:
+            ```json
+            ${{ toJson(needs.params.outputs) }}
+            ```
+
+            **Commits since last release:** TODO
+          draft: false
+          prerelease: false
+
+
+upload-builds:
+    needs: [create-release]
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        config:
+          # These should match the configurations defined in the build job
+          # TODO: figure out how to DRY these configurations
+          - os: ubuntu-latest
+            artifact_name: "Linux-64bit"
+            artifact_relpath: "/desktop/release/linux/Fractal"
+         - os: windows-latest
+           artifact_name: "Windows-64bit"
+           artifact_relpath: "/desktop/release/windows/Fractal.exe"
+         - os: macos-latest
+           artifact_name: "macOS-64bit"
+           artifact_relpath: "/desktop/release/mac/Fractal.app"
+    name: Upload ${{ matrix.config.artifact_name }} to release ${{ needs['create-release'].outputs.version_id }}
+    steps:
+      - name: Retrieve artifact ${{ matrix.config.artifact_name }}
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{ matrix.config.artifact_name }}
+          path: ${{ matrix.config.artifact_name }}
+      - name: Package up artifact as a zip file
+        run: |
+          ls -laR
+          zip -r "${{ matrix.config.artifact_name }}" "${{ matrix.config.artifact_name }}"
+      - name: Upload to release ${{ needs['create-release'].outputs.version_id }}
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ needs['create-release'].outputs.release_upload_url }}
+          asset_path: ./${{ matrix.config.artifact_name }}.zip
+          asset_name: protocol_${{ needs['create-release'].outputs.version_id }}_${{ matrix.config.artifact_name }}.zip
+          asset_content_type: application/zip
