add missing sentry hook to brave extension and lowercase file

diff --git a/mandelboxes/browsers/base-chromium/lowercase-chromium-files b/mandelboxes/browsers/base-chromium/lowercase-chromium-files
--- a/mandelboxes/browsers/base-chromium/lowercase-chromium-files
+++ b/mandelboxes/browsers/base-chromium/lowercase-chromium-files
@@ -1,5 +1,20 @@
 #!/bin/bash
 
+# Enable Sentry bash error handler, this will catch errors if `set -e` is set in a Bash script
+SENTRY_ENV_FILENAME=/usr/share/whist/private/sentry_env
+case $(cat $SENTRY_ENV_FILENAME) in
+  dev|staging|prod)
+    export SENTRY_ENVIRONMENT=${SENTRY_ENV}
+    eval "$(sentry-cli bash-hook)"
+    ;;
+  *)
+    echo "Sentry environment not set, skipping Sentry error handler"
+    ;;
+esac
+
+# Exit on subcommand errors
+set -Eeuo pipefail
+
 monitor() {
   inotifywait -q -m -r -e create "$1" | while read DIRECTORY EVENT FILE; do
     case $EVENT in
