:checkered_flag: install patched libinput and xf86-input-libinput
this enables the high-resolution scroll events which are reported
by the kernel to now be interpreted by libinput and passed to X11.
google chrome can now interpret high-resolution scroll events that
originate from the client protocol!

diff --git a/container-images/base/Dockerfile.20 b/container-images/base/Dockerfile.20
--- a/container-images/base/Dockerfile.20
+++ b/container-images/base/Dockerfile.20
@@ -1,4 +1,169 @@
-FROM ubuntu:20.04
+################ STAGE 1: libinput-build ################
+# - Install build dependencies as per the documentation
+#   at https://wayland.freedesktop.org/libinput/doc/latest/building.html#build-dependencies-per-distribution
+# - Download libinput source and hi-res scrolling patch
+#   as per https://aur.archlinux.org/packages/libinput-hires-scroll
+# - Configure and build patched libinput
+# EXPOSES patched .deb build of libinput for later stages
+#########################################################
+FROM ubuntu:20.04 as libinput-build
+
+# Force failure on non-zero exit code for commands with a pipe in them
+SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
+
+ENV container docker
+ENV LC_ALL C
+ENV DEBIAN_FRONTEND noninteractive
+
+RUN sed -i 's/# deb/deb/g' /etc/apt/sources.list
+
+RUN apt-get update \
+    && apt-get autoremove -y \
+    && apt-get clean \
+    && rm -rf /tmp/* /var/tmp/*
+
+# Install build dependencies for libinput
+RUN apt-get install --no-install-recommends -y \
+    git \
+    gcc \
+    g++ \
+    pkg-config \
+    meson \
+    check \
+    libudev-dev \
+    libevdev-dev \
+    doxygen \
+    graphviz \
+    python3-sphinx \
+    python3-recommonmark \
+    python3-sphinx-rtd-theme \
+    python3-pytest-xdist \
+    libwacom-dev \
+    libcairo2-dev \
+    libgtk-3-dev \
+    libglib2.0-dev \
+    libmtdev-dev \
+    wget \
+    xz-utils \
+    patch \
+    && apt-get autoremove -y \
+    && apt-get clean \
+    && rm -rf /tmp/* /var/tmp/*
+
+# Retrieve patches for libinput source
+COPY depends/libinput/patch/hi-res-scroll.patch hi-res-scroll.patch
+
+# Download and patch libinput source
+RUN wget -qO - https://freedesktop.org/software/libinput/libinput-1.15.5.tar.xz \
+    | tar xJ \
+    && cd libinput-1.15.5 \
+    && patch -i /hi-res-scroll.patch -Np1 \
+    && rm /hi-res-scroll.patch
+
+# Configure and build libinput
+RUN meson libinput-1.15.5 build \
+    --prefix=/usr \
+    --libdir=/usr/lib \
+    -D udev-dir=/usr/lib/udev \
+    -D tests=false \
+    -D documentation=false \
+    && ninja -C build
+
+# Install libinput to package folder
+RUN mkdir /libinput-fractal \
+    && DESTDIR=/libinput-fractal ninja -C build install
+
+# Setup debian package information
+COPY depends/libinput/debian/control /libinput-fractal/DEBIAN/control
+
+# Build debian package
+RUN dpkg-deb --build libinput-fractal
+
+################ STAGE 2: xf86-input-libinput-build ################
+# - Install build dependencies as per the documentation
+#   at https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput
+# - For libinput dependency, copy and install libinput from the
+#   libinput-build stage
+# - Download xf86-input-libinput source and hi-res scrolling
+#   patch as per https://aur.archlinux.org/packages/xf86-input-libinput-hires-scroll
+# - Configure and build patched xf86-input-libinput
+# EXPOSES patched build of xf86-input-libinput
+####################################################################
+FROM ubuntu:20.04 as xf86-input-libinput-build
+
+# Force failure on non-zero exit code for commands with a pipe in them
+SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
+
+ENV container docker
+ENV LC_ALL C
+ENV DEBIAN_FRONTEND noninteractive
+
+RUN sed -i 's/# deb/deb/g' /etc/apt/sources.list
+
+RUN apt-get update \
+    && apt-get autoremove -y \
+    && apt-get clean \
+    && rm -rf /tmp/* /var/tmp/*
+
+# Copy patched libinput package
+COPY --from=libinput-build libinput-fractal.deb /
+
+# Install build dependencies
+# This includes patched libinput
+RUN apt-get update && apt-get install --no-install-recommends -y \
+    xorg-dev \
+    xutils-dev \
+    libudev-dev \
+    wget \
+    patch \
+    ca-certificates \
+    make \
+    automake \
+    autoconf \
+    libtool \
+    ./libinput-fractal.deb \
+    && apt-get autoremove -y \
+    && apt-get clean \
+    && rm -rf /tmp/* /var/tmp/*
+
+# Retrieve patches for xf86-input-libiput source
+COPY depends/xf86-input-libinput/patch/hi-res-scroll.patch hi-res-scroll.patch
+
+# Download and patch xf86-input-libinput source
+RUN wget -qO - https://xorg.freedesktop.org/releases/individual/driver/xf86-input-libinput-0.29.0.tar.bz2 \
+    | tar xj \
+    && cd xf86-input-libinput-0.29.0 \
+    && patch -i /hi-res-scroll.patch -Np1 \
+    && rm /hi-res-scroll.patch
+
+# Configure and build patched xf86-input-libinput
+RUN cd xf86-input-libinput-0.29.0 \
+    && autoreconf -vif \
+    && ./configure \
+       --disable-static \
+       --prefix=/usr \
+    && make -j
+
+# Install xf86-input-libinput to package folder
+RUN mkdir /xf86-input-libinput-fractal \
+    && cd xf86-input-libinput-0.29.0 \
+    && make DESTDIR=/xf86-input-libinput-fractal install
+
+# Setup debian package information
+COPY depends/xf86-input-libinput/debian/control /xf86-input-libinput-fractal/DEBIAN/control
+
+# Build debian package
+RUN dpkg-deb --build xf86-input-libinput-fractal
+
+################ STAGE 3: fractal-base ################
+# - Copy and install libinput from libinput-build
+# - Copy and install xf86-input-libinput from
+#   xf86-input-libinput-build
+# - Install and configure all necessary components for
+#   our base container image
+# EXPOSES all of fractal-base as the final image
+#######################################################
+FROM ubuntu:20.04 as fractal-base
 
 # Force failure on non-zero exit code for commands with a pipe in them
 SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
@@ -39,6 +204,22 @@ RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
     /lib/systemd/system/anaconda.target.wants/* \
     /lib/systemd/system/plymouth* \
     /lib/systemd/system/systemd-update-utmp*
+
+# Install libinput driver for XServer input
+# This must happen very early to preempt conflicts with
+# upstream packages such as libinput10 and libinput-bin
+
+# Copy patched libinput and xf86-input-libinput
+COPY --from=libinput-build /libinput-fractal.deb /deb/libinput-fractal.deb
+COPY --from=xf86-input-libinput-build /xf86-input-libinput-fractal.deb deb/xf86-input-libinput-fractal.deb
+
+# Install patched libinput and xf86-input-libinput
+RUN apt-get install --no-install-recommends -y \
+    ./deb/libinput-fractal.deb \
+    ./deb/xf86-input-libinput-fractal.deb \
+    && apt-get autoremove -y \
+    && apt-get clean \
+    && rm -rf /tmp/* /var/tmp/* /deb
 
 # Install some useful utilities and their dependencies for debugging/testing
 # These packages need to be installed before installing/updating Python
@@ -185,15 +366,6 @@ RUN apt-get install --allow-downgrades --no-install-recommends -y \
     libcurl4 \
     curl \
     jq \
-    && apt-get autoremove -y \
-    && apt-get clean \
-    && rm -rf /tmp/* /var/tmp/*
-
-# Install libinput driver for XServer input.
-# For some reason, this installation does not work if included with the previous
-# commands.
-RUN apt-get install --no-install-recommends -y \
-    xserver-xorg-input-libinput \
     && apt-get autoremove -y \
     && apt-get clean \
     && rm -rf /tmp/* /var/tmp/*
