good hadolint setup

diff --git a/container-images/creative/figma/Dockerfile.20 b/container-images/creative/figma/Dockerfile.20
--- a/container-images/creative/figma/Dockerfile.20
+++ b/container-images/creative/figma/Dockerfile.20
@@ -6,6 +6,9 @@
 ##########################################################
 FROM fractal/browsers/chrome:current-build as figma-1
 
+# Force failure on non-zero exit code for commands with a pipe in them
+SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
+
 # Install Figma build dependencies explicitly
 RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
     unzip \
@@ -39,6 +42,9 @@ RUN ELECTRON_V="v$(cat electron.v)" \
 # EXPOSES bindings.node to figma-2 to provide getFonts() to Figma
 ###################################################################
 FROM ubuntu:20.04 as bindings-builder
+
+# Force failure on non-zero exit code for commands with a pipe in them
+SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
 
 # Install Figma Font Bindings build dependencies explicitly
 RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
@@ -77,6 +83,9 @@ RUN ELECTRON_V="$(cat electron.v)" \
 # EXPOSES all of figma-2 as the final image
 ##########################################################
 FROM figma-1 as figma-2
+
+# Force failure on non-zero exit code for commands with a pipe in them
+SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
 
 # Copy bindings.node from bindings-builder stage into Figma directory
 COPY --from=bindings-builder bindings.node tmp/build/build/Release/bindings.node
diff --git a/container-images/productivity/notion/Dockerfile.20 b/container-images/productivity/notion/Dockerfile.20
--- a/container-images/productivity/notion/Dockerfile.20
+++ b/container-images/productivity/notion/Dockerfile.20
@@ -1,5 +1,8 @@
 FROM fractal/browsers/chrome:current-build
 
+# Force failure on non-zero exit code for commands with a pipe in them
+SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
+
 # Install Notion dependencies explicitly
 RUN curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -
 RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
