Implement Hadolint for linting our Dockerfiles (#563)
* add basics for Dockerfile linting with hadolint

* good hadolint setup

* more dockerfiles quality

* finished clearing hadolint warnings in our dockerfiles

* precommit

* newline

* remove extra \

* rename file and add sudo permission

* run hadolint with sudo

* call hadolint explicitly and use latest version

* ./ to run

* no usr

* let's just simplify things

* add execution permission

* force permission with sudo

* use macos to make hadolint easier

* just *

* single quotes for blob

* no quote and no ./

* log paths

* more logging

* run in hadolint container

* remove homebrew

* use script smh

* chmod +x

* logging

* working dir

* test

* remove script

* test hardcoded path

* build up the glob progressively

* do single glob

* try with quotes

* do the dummy way and move on

* attempt slightly less dummy approach

* streamline a bit

* lint

* alright, done

* replacte ls | grep

* add quotes

* re-add the readme, which somehow was deleted

* re-add ls | grep but inline ignore hadolint only there

Co-authored-by: Philippe Noel <phil@tryfractal.com>

diff --git a/container-images/browsers/sidekick/Dockerfile.20 b/container-images/browsers/sidekick/Dockerfile.20
--- a/container-images/browsers/sidekick/Dockerfile.20
+++ b/container-images/browsers/sidekick/Dockerfile.20
@@ -1,5 +1,8 @@
 FROM fractal/base:current-build
 
+# Force failure on non-zero exit code for commands with a pipe in them
+SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
+
 # Download Sidekick installer
 RUN wget -qO sidekick.deb https://api.meetsidekick.com/downloads/df/linux/deb
 
@@ -23,4 +26,4 @@ RUN su - fractal -c "mkdir -p /home/fractal/.config/sidekick \
     && touch /home/fractal/.config/sidekick/'First Run'"
 
 # Setup Fractal application symlink
-RUN ln -sf $(which sidekick-browser) /usr/bin/fractal-application
+RUN ln -sf "$(which sidekick-browser)" /usr/bin/fractal-application
diff --git a/container-images/creative/gimp/Dockerfile.20 b/container-images/creative/gimp/Dockerfile.20
--- a/container-images/creative/gimp/Dockerfile.20
+++ b/container-images/creative/gimp/Dockerfile.20
@@ -1,5 +1,8 @@
 FROM fractal/base:current-build
 
+# Force failure on non-zero exit code for commands with a pipe in them
+SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
+
 # Install Gimp and its dependencies explicitly
 RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
     libgimp2.0 \
@@ -13,4 +16,4 @@ COPY --chown=fractal gimprc /home/fractal/.config/GIMP/2.10/gimprc
 COPY gimprc /root/.config/GIMP/2.10/gimprc
 
 # Setup Fractal application symlink
-RUN ln -sf $(which gimp) /usr/bin/fractal-application
+RUN ln -sf "$(which gimp)" /usr/bin/fractal-application
diff --git a/container-images/creative/texturelab/Dockerfile.20 b/container-images/creative/texturelab/Dockerfile.20
--- a/container-images/creative/texturelab/Dockerfile.20
+++ b/container-images/creative/texturelab/Dockerfile.20
@@ -1,5 +1,8 @@
 FROM fractal/base:current-build
 
+# Force failure on non-zero exit code for commands with a pipe in them
+SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
+
 # Install TextureLab build dependencies
 RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
     unzip \
@@ -10,8 +13,8 @@ RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends
     && rm -rf /var/lib/apt/lists/*
 
 # Add yarn to apt
-RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - \
-    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
+RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
+    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
 
 # Install yarn
 RUN apt-get update && apt-get install --allow-downgrades --no-install-recommends -y \
