Add Sentry to Mandelboxes (#4584)
* will this automatically propagate to all scripts/service or need to be added directly

* augment sentry releases workflow

* install curl before sentry

* use wget instead

* run script directly?

* test

* add no check certificate

* switch to curl since it is necessary

* just do both atop tbh

* install certificates

* add missing -

* stop messing with things that are working

* test sentry error catching

* sending sentry event works, let's test hook handler

* add eval directly, needs testing

* use script to start audio, like with other services, so sentry can be enabled

* proper path for pulseaudio bash script

* remove audio bash script, remove sentry hook from dockerfiles (doesn't work) and test scripts (not needed)

* add sentry framework to the python script

* linted

* add sentry test for python

* import sentry_sdk, oops

* install sentry_sdk in tests temporarily just to test sentry works

* remove entrypoint sentry test, it works

* remove sentry python test, untested

* try again without pipefail and without exec

* seems like it build, re-enable pipefail

* remove Sentry from xinitrc

* small typo, fix typecasting

* clang-format

diff --git a/mandelboxes/development/benchmark/Dockerfile.20 b/mandelboxes/development/benchmark/Dockerfile.20
--- a/mandelboxes/development/benchmark/Dockerfile.20
+++ b/mandelboxes/development/benchmark/Dockerfile.20
@@ -3,8 +3,13 @@ ARG BuildAssetPackage "protocol"
 FROM fractal/build-assets:$BuildAssetPackage as build-assets
 FROM fractal/browsers/chrome:current-build as fractal-dev-benchmark
 
-# Copies the video file, html file to enable looping, and the benchmark start-chrome
+# Force failure on non-zero exit code for commands with a pipe in them
+SHELL ["/bin/bash", "-Eeuo", "pipefail", "-c"]
+
+# Retrieve the video file
 RUN curl https://fractal-test-assets.s3.amazonaws.com/bbb-1080p-75.mp4 -o /home/fractal/bbb-1080p.mp4
+
+# Copy the HTML file (to enable looping) and the benchmark start-chrome.sh script
 COPY 1080p_60fps.html /home/fractal/1080p_60fps.html
 COPY start-chrome.sh /usr/bin/start-chrome
 RUN chmod +x /usr/bin/start-chrome
