ensures update region was called successfully and poll_task is never called on an invalid ID

diff --git a/.github/workflows/fractal-publish-ami.yml b/.github/workflows/fractal-publish-ami.yml
--- a/.github/workflows/fractal-publish-ami.yml
+++ b/.github/workflows/fractal-publish-ami.yml
@@ -119,12 +119,17 @@ jobs:
                       -H "Content-Type: application/json" \
                       -H "Authorization: Bearer ${token}" \
                       --data "{\"region_name\": \"${region}\"}" \
-                      "${{ env.webserver_url }}aws_container/update_region" | jq -er ".ID") # the -e flag is to make sure it fails if there isn't a task ID
+                      "${{ env.webserver_url }}aws_container/update_region" | jq -er ".ID") # the -e option makes jq return with error code 1 if element not found
 
-                    # verify update_region succeeded
+                    # ensures update_region was called successfully
+                    if [[ $? =~ 1 ]]; then
+                      echo "Failed to update $region" && false
+                    fi
+
+                    # poll for update_region and its subtasks 
                     bash poll_task.sh ${{ env.webserver_url}} ${ celery_task_output_id }
                     if [[ $? =~ 1 ]]; then
-                      echo "Failed to update region $region" && false
+                      echo "Failed to update $region" && false
                     fi
 
                   done
