make all jobs workflow dispatchable

diff --git a/.github/workflows/fractal-build-and-deploy.yml b/.github/workflows/fractal-build-and-deploy.yml
--- a/.github/workflows/fractal-build-and-deploy.yml
+++ b/.github/workflows/fractal-build-and-deploy.yml
@@ -143,21 +143,20 @@ jobs:
 
           # Store job dependency files
           declare -A job_dependencies
+
           # If "" is given, then the whole repo will be a dependency
-
-          # TODO: ADD MISSING JOBS HERE
-
-          # jobs fractal-publish-build-config, fractal-build-monorepo-config, client-applications-notify-slack, fractal-create-github-release-tag
-
           job_dependencies[mandelboxes-and-amis-publish-ghcr-and-aws]="host-setup host-service protocol mandelboxes"
-          job_dependencies[webserver-spin-up-new-buffer]="TODO"
-          job_dependencies[webserver-swap-active-amis]="TODO"
           job_dependencies[webserver-deploy-heroku]="webserver"
-          job_dependencies[client-applications-update-version-number]="TODO"
+          job_dependencies[webserver-spin-up-new-buffer]="webserver host-setup host-service protocol mandelboxes"
           job_dependencies[client-applications-publish-build-x64-s3]="protocol client-applications core-ts"
           job_dependencies[client-applications-publish-build-arm64-s3]="protocol client-applications core-ts"
-          job_dependencies[client-applications-retrieve-version-number]="TODO"
+          job_dependencies[webserver-swap-active-amis]="webserver host-setup host-service protocol mandelboxes"
           job_dependencies[microservices-deploy-auth0-rules]="microservices"
+
+          # The jobs `fractal-publish-build-config`, `fractal-build-monorepo-config`,
+          # `client-applications-retrieve-version-nubmer`, `client-applications-update-version-number`,
+          # `client-applications-notify-slack`, and `fractal-create-github-release-tag`
+          # are not set above as workflow_dispatch-able since they don't make when run on their own
 
           # Files that all jobs depend on
           universal_dependencies=".github/workflows/fractal-build-and-deploy.yml"
@@ -554,6 +553,123 @@ jobs:
   #######################################################################################
   #######################################################################################
 
+  # Webserver: Deploy to Heroku
+  # Push the webserver subtree to the appropriate Heroku app.
+  webserver-deploy-heroku:
+    name: "Webserver: Deploy to Heroku"
+    runs-on: ubuntu-20.04
+    concurrency: webserver-deploy-heroku-${{ github.ref }}
+    needs: [fractal-publish-build-config]
+    if: contains(needs.fractal-publish-build-config.outputs.jobs, '|webserver-deploy-heroku|')
+
+    steps:
+      - name: Checkout Git Repository
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0 # need to get full history for splitsh-lite
+
+      - name: Setup Python-based notifications
+        working-directory: .github/workflows/helpers
+        run: ./notifications/setup_notifications.sh
+
+      - name: Authenticate Heroku
+        run: |
+          cat > ~/.netrc << EOF
+          machine api.heroku.com
+            login ${{ secrets.HEROKU_DEVELOPER_LOGIN_EMAIL }}
+            password ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
+          machine git.heroku.com
+            login ${{ secrets.HEROKU_DEVELOPER_LOGIN_EMAIL }}
+            password ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
+          EOF
+
+      - name: Add Heroku Remote
+        env:
+          HEROKU_API_KEY: ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
+        run: |
+          if [[ ${{ needs.fractal-publish-build-config.outputs.branch }} == dev ]]; then
+              HEROKU_APP_NAME=fractal-dev-server
+          elif [[ ${{ needs.fractal-publish-build-config.outputs.branch }} == staging ]]; then
+              HEROKU_APP_NAME=fractal-staging-server
+          elif [[ ${{ needs.fractal-publish-build-config.outputs.branch }} == prod ]]; then
+              HEROKU_APP_NAME=fractal-prod-server
+          else
+              echo 'Error: Invalid branch' && false
+          fi
+          echo "HEROKU_APP_NAME=$HEROKU_APP_NAME" >> $GITHUB_ENV
+
+          heroku git:remote --app $HEROKU_APP_NAME --remote heroku-fractal-server
+
+      - name: Install splitsh-lite for Subtree Split
+        run: >
+          wget -qO - https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz
+          | sudo tar -zxp --directory /usr/local/bin/
+
+      - name: Diff database schema with local schema.sql
+        id: db-diff
+        env:
+          HEROKU_API_TOKEN: ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
+          HEROKU_APP_NAME: ${{ env.HEROKU_APP_NAME }}
+        uses: ./.github/actions/db-migration
+
+      - name: Deploy the Webserver Atomically & Migrate DB Schema (as needed)
+        if: needs.fractal-publish-build-config.outputs.publish == 'true'
+        env:
+          HEROKU_APP_NAME: ${{ env.HEROKU_APP_NAME }}
+        shell: bash --noprofile --norc -eo pipefail {0}
+        run: |
+          webserver/atomic_deployment.sh $HEROKU_APP_NAME '${{ steps.db-diff.outputs.code }}' '${{ steps.db-diff.outputs.diff }}'
+
+      - name: Notify Slack on Database Migration Performed
+        shell: python3 {0}
+        run: |
+          import os
+          import sys
+          import urllib.parse
+          from notifications.slack_bot import slack_post
+
+          # This should be set by webserver/atomic_deployment.sh
+          if os.environ.get("DB_MIGRATION_PERFORMED", "false") != "true":
+            sys.exit(0)
+
+          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT }}"
+          SLACK_CHANNEL = "#alerts-${{ needs.fractal-publish-build-config.outputs.branch }}"
+
+          TITLE = ":construction: Database Migration Performed :construction:"
+          BODY = f"Database Schema Migration performed on branch: `${{ needs.fractal-publish-build-config.outputs.branch }}` (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
+
+          slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY, title=TITLE)
+
+      - name: Notify Slack on Successful Webserver Deploy
+        if: needs.fractal-publish-build-config.outputs.publish == 'true'
+        shell: python3 {0}
+        run: |
+          import os
+          from notifications.slack_bot import slack_post
+
+          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT }}"
+          SLACK_CHANNEL = "#alerts-${{ needs.fractal-publish-build-config.outputs.branch }}"
+          HEROKU_APP_NAME = os.environ["HEROKU_APP_NAME"]
+          TITLE = ":heroku: Webserver Deployed :heroku:"
+          BODY = f"Webserver deployed to Heroku app `{HEROKU_APP_NAME}` on branch: `${{ needs.fractal-publish-build-config.outputs.branch }}` (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
+
+          slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY, title=TITLE)
+
+      - name: Notify Slack on Job Error
+        if: failure()
+        shell: python3 {0}
+        run: |
+          from notifications.slack_bot import slack_post
+
+          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT }}"
+          SLACK_CHANNEL = "#alerts-${{ needs.fractal-publish-build-config.outputs.branch }}"
+          BODY = "@releases :rotating_light: Deployment failed: could not deploy Webserver in `webserver-deploy-heroku` job, investigate immediately :rotating_light: (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
+
+          slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY)
+
+  #######################################################################################
+  #######################################################################################
+
   # Uses webserver's cli command to update AMIs if new AMIs have been built
   webserver-spin-up-new-buffer:
     name: "Create buffers for new AMIs using Webserver"
@@ -562,8 +678,8 @@ jobs:
     needs:
       [
         fractal-publish-build-config,
-        webserver-deploy-heroku,
         mandelboxes-and-amis-publish-ghcr-and-aws,
+        webserver-deploy-heroku,
       ]
     outputs:
       new_amis_str: ${{ steps.run-webserver-cli-ami-upgrade.outputs.new_amis}}
@@ -690,10 +806,10 @@ jobs:
     concurrency: webserver-swap-active-amis-${{ github.ref }}
     needs:
       [
+        fractal-publish-build-config,
+        webserver-spin-up-new-buffer,
         client-applications-publish-build-x64-s3,
         client-applications-publish-build-arm64-s3,
-        webserver-spin-up-new-buffer,
-        fractal-publish-build-config,
       ]
     if: always() && (needs.client-applications-publish-build-x64-s3.result == 'success' && needs.client-applications-publish-build-arm64-s3.result == 'success') && (needs.webserver-spin-up-new-buffer.result == 'success')
     env:
@@ -798,123 +914,6 @@ jobs:
           WEBSERVER_URL = "${{ needs.fractal-publish-build-config.outputs.webserver_url }}"
           BRANCH_NAME = "${{ needs.fractal-publish-build-config.outputs.branch }}"
           BODY = f"@releases :rotating_light: Webserver at {WEBSERVER_URL} failed to swap over active AMIs, investigate immediately :rotating_light: (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
-
-          slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY)
-
-  #######################################################################################
-  #######################################################################################
-
-  # Webserver: Deploy to Heroku
-  # Push the webserver subtree to the appropriate Heroku app.
-  webserver-deploy-heroku:
-    name: "Webserver: Deploy to Heroku"
-    runs-on: ubuntu-20.04
-    concurrency: webserver-deploy-heroku-${{ github.ref }}
-    needs: [fractal-publish-build-config]
-    if: contains(needs.fractal-publish-build-config.outputs.jobs, '|webserver-deploy-heroku|')
-
-    steps:
-      - name: Checkout Git Repository
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0 # need to get full history for splitsh-lite
-
-      - name: Setup Python-based notifications
-        working-directory: .github/workflows/helpers
-        run: ./notifications/setup_notifications.sh
-
-      - name: Authenticate Heroku
-        run: |
-          cat > ~/.netrc << EOF
-          machine api.heroku.com
-            login ${{ secrets.HEROKU_DEVELOPER_LOGIN_EMAIL }}
-            password ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
-          machine git.heroku.com
-            login ${{ secrets.HEROKU_DEVELOPER_LOGIN_EMAIL }}
-            password ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
-          EOF
-
-      - name: Add Heroku Remote
-        env:
-          HEROKU_API_KEY: ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
-        run: |
-          if [[ ${{ needs.fractal-publish-build-config.outputs.branch }} == dev ]]; then
-              HEROKU_APP_NAME=fractal-dev-server
-          elif [[ ${{ needs.fractal-publish-build-config.outputs.branch }} == staging ]]; then
-              HEROKU_APP_NAME=fractal-staging-server
-          elif [[ ${{ needs.fractal-publish-build-config.outputs.branch }} == prod ]]; then
-              HEROKU_APP_NAME=fractal-prod-server
-          else
-              echo 'Error: Invalid branch' && false
-          fi
-          echo "HEROKU_APP_NAME=$HEROKU_APP_NAME" >> $GITHUB_ENV
-
-          heroku git:remote --app $HEROKU_APP_NAME --remote heroku-fractal-server
-
-      - name: Install splitsh-lite for Subtree Split
-        run: >
-          wget -qO - https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz
-          | sudo tar -zxp --directory /usr/local/bin/
-
-      - name: Diff database schema with local schema.sql
-        id: db-diff
-        env:
-          HEROKU_API_TOKEN: ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
-          HEROKU_APP_NAME: ${{ env.HEROKU_APP_NAME }}
-        uses: ./.github/actions/db-migration
-
-      - name: Deploy the Webserver Atomically & Migrate DB Schema (as needed)
-        if: needs.fractal-publish-build-config.outputs.publish == 'true'
-        env:
-          HEROKU_APP_NAME: ${{ env.HEROKU_APP_NAME }}
-        shell: bash --noprofile --norc -eo pipefail {0}
-        run: |
-          webserver/atomic_deployment.sh $HEROKU_APP_NAME '${{ steps.db-diff.outputs.code }}' '${{ steps.db-diff.outputs.diff }}'
-
-      - name: Notify Slack on Database Migration Performed
-        shell: python3 {0}
-        run: |
-          import os
-          import sys
-          import urllib.parse
-          from notifications.slack_bot import slack_post
-
-          # This should be set by webserver/atomic_deployment.sh
-          if os.environ.get("DB_MIGRATION_PERFORMED", "false") != "true":
-            sys.exit(0)
-
-          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT }}"
-          SLACK_CHANNEL = "#alerts-${{ needs.fractal-publish-build-config.outputs.branch }}"
-
-          TITLE = ":construction: Database Migration Performed :construction:"
-          BODY = f"Database Schema Migration performed on branch: `${{ needs.fractal-publish-build-config.outputs.branch }}` (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
-
-          slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY, title=TITLE)
-
-      - name: Notify Slack on Successful Webserver Deploy
-        if: needs.fractal-publish-build-config.outputs.publish == 'true'
-        shell: python3 {0}
-        run: |
-          import os
-          from notifications.slack_bot import slack_post
-
-          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT }}"
-          SLACK_CHANNEL = "#alerts-${{ needs.fractal-publish-build-config.outputs.branch }}"
-          HEROKU_APP_NAME = os.environ["HEROKU_APP_NAME"]
-          TITLE = ":heroku: Webserver Deployed :heroku:"
-          BODY = f"Webserver deployed to Heroku app `{HEROKU_APP_NAME}` on branch: `${{ needs.fractal-publish-build-config.outputs.branch }}` (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
-
-          slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY, title=TITLE)
-
-      - name: Notify Slack on Job Error
-        if: failure()
-        shell: python3 {0}
-        run: |
-          from notifications.slack_bot import slack_post
-
-          SLACK_WEBHOOK = "${{ secrets.SLACK_HOOKS_ENDPOINT }}"
-          SLACK_CHANNEL = "#alerts-${{ needs.fractal-publish-build-config.outputs.branch }}"
-          BODY = "@releases :rotating_light: Deployment failed: could not deploy Webserver in `webserver-deploy-heroku` job, investigate immediately :rotating_light: (<https://github.com/fractal/fractal/actions/runs/${{ github.run_id }} | see logs>)"
 
           slack_post(slack_webhook=SLACK_WEBHOOK, channel=SLACK_CHANNEL, body=BODY)
 
