integrated ami-building with fractal-build-and-deploy.yml

diff --git a/.github/workflows/fractal-build-and-deploy.yml b/.github/workflows/fractal-build-and-deploy.yml
--- a/.github/workflows/fractal-build-and-deploy.yml
+++ b/.github/workflows/fractal-build-and-deploy.yml
@@ -263,58 +263,161 @@ jobs:
                   --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Fractal Bot\", \"text\": \":spiral_note_pad: Task Definitions rendered and deployed to ${{ needs.fractal-publish-build-config.outputs.deploy_environment }} via ECS upload :bezos:\", \"icon_emoji\": \":fractal:\"}" \
                   ${{ secrets.SLACK_HOOKS_ENDPOINT }}
 
-    # ECS Host Service: Build & Publish to AWS S3
-    # Build and publish the ECS host service to an S3 bucket from which EC2 hosts pull.
-    # Runs if config succeeds and branch is in ["master"] and publish-images-ghcr succeeds.
-    ecs-host-service-publish-build-s3:
-        name: "ECS Host Service: Build & Publish to AWS S3"
-        runs-on: ubuntu-20.04
-        needs:
-            [fractal-publish-build-config, container-images-publish-images-ghcr]
+    # AMI: Build and Publish to AWS EC2
+    # Build and publish the Fractal Linux AMI, containing the ECS Host Service, to all supported AWS EC2 regions. 
+    # Runs if config succeeds and branch is in ["master", "staging", "dev"] and publish-images-ghcr succeeds.
+    ami-publish-ec2:
+      name: "AMI: Build & Publish to AWS EC2"
+      runs-on: ubuntu-20.04
+      needs: [fractal-publish-build-config, container-images-publish-images-ghcr]
+      if: >
+          contains(fromJSON('["master", "staging", "dev"]'), needs.fractal-publish-build-config.outputs.branch) &&
+          contains(fromJSON('["all", "ami-publish-ec2"]'), needs.fractal-publish-build-config.outputs.job)
+      env:
+          aws_new_ami_source_region: us-east-1 # The AWS region our new AMI gets built in, our initial AWS supported region
+          aws_new_ami_instance_type: g3.4xlarge # The AWS EC2 instance type our new AMI gets built on (must be the EC2 instance type we run in production)
+          aws_new_ami_subnet_id: subnet-3341731d # The subnetwork, within the VPC, within which the EC2 instance building our new AMI runs
+          aws_new_ami_vpc_id: vpc-34aded4e # The ID of the Fractal-created VPC the EC2 instance building the AMI is part of
+          aws_source_ami_id: ami-0885b1f6bd170450c # The base AWS-provided AMI we build our AMI from: AWS Ubuntu Server 20.04 LTS
+
+          # The regions our new AMI gets cloned to (should be all our other supported AWS regions)
+          # defined as a formatted json array to be copied into ami_config.json directly
+          aws_additional_supported_regions: "[\\\"us-east-2\\\",\\\"us-west-1\\\",\\\"us-west-2\\\",\\\"ca-central-1\\\",\\\"eu-west-1\\\",\\\"eu-central-1\\\"]"
+
+      steps:
+          - name: Checkout Git Repository
+            uses: actions/checkout@v2
+
+          ######################## Building ECS Host Service ########################
+
+          # To build ECS Host Service
+          - name: Setup Go environment
+            uses: actions/setup-go@v2.1.3
+
+          - name: Install Go dependencies
+            working-directory: ecs-host-service
+            run: make deps
+
+          - name: Build Go project
+            env:
+                WEBSERVER_AUTH_SECRET_DEV: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_DEV }}
+                WEBSERVER_AUTH_SECRET_STAGING: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_STAGING }}
+                WEBSERVER_AUTH_SECRET_PROD: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_PROD }}
+            working-directory: ecs-host-service
+            run: make build
+
+          ###########################################################################
+
+          - name: Retrieve Current Git Hash as Environment Variable
+            run: echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV
+
+          - name: Configure AWS CLI
+            uses: aws-actions/configure-aws-credentials@v1
+            with:
+                aws-access-key-id: ${{ secrets.AWS_EC2_S3_ACCESS_KEY_ID }}
+                aws-secret-access-key: ${{ secrets.AWS_EC2_S3_SECRET_ACCESS_KEY }}
+                aws-region: ${{ env.aws_new_ami_source_region }}
+
+          - name: Set Appropriate GraphQL URL and Access Key (prod, staging, dev) Based on Git Branch (master, staging, dev)
+            run: |
+                if [ "${GITHUB_REF##*/}" == "master" ]; then
+                  echo "graphql_db_url=https://prod-database.fractal.co/v1/graphql" >> $GITHUB_ENV
+                  echo "hasura_graphql_access_key=${{ secrets.HASURA_GRAPHQL_ACCESS_KEY_PROD }}" >> $GITHUB_ENV
+                  echo "webserver_url=https://prod-server.fractal.co/" >> $GITHUB_ENV
+                elif [ "${GITHUB_REF##*/}" == "staging" ]; then
+                  echo "graphql_db_url=https://staging-database.fractal.co/v1/graphql" >> $GITHUB_ENV
+                  echo "hasura_graphql_access_key=${{ secrets.HASURA_GRAPHQL_ACCESS_KEY_STAGING }}" >> $GITHUB_ENV
+                  echo "webserver_url=https://staging-server.fractal.co/" >> $GITHUB_ENV
+                else
+                  echo "graphql_db_url=https://dev-database.fractal.co/v1/graphql" >> $GITHUB_ENV
+                  echo "hasura_graphql_access_key=${{ secrets.HASURA_GRAPHQL_ACCESS_KEY_DEV }}" >> $GITHUB_ENV
+                  echo "webserver_url=https://dev-server.fractal.co/" >> $GITHUB_ENV
+                fi
+
+          # no quotes around ${{ env.aws_additional_supported_regions }} because ami_regions expects list
+          - name: Generate ami_config.json Packer Config File for Building New AMI
+            working-directory: ecs-host-setup
+            run: >
+                cat ami_config.json
+                | jq -c ".builders[0].secret_key = \"${{ secrets.AWS_EC2_SECRET_ACCESS_KEY}}\""
+                | jq -c ".builders[0].access_key = \"${{ secrets.AWS_EC2_ACCESS_KEY_ID }}\""
+                | jq -c ".builders[0].ami_name = \"ami-us-east-1-${{ env.commit_sha }}\""
+                | jq -c ".builders[0].region = \"${{ env.aws_new_ami_source_region }}\""
+                | jq -c ".builders[0].instance_type = \"${{ env.aws_new_ami_instance_type }}\""
+                | jq -c ".builders[0].subnet_id = \"${{ env.aws_new_ami_subnet_id }}\""
+                | jq -c ".builders[0].vpc_id = \"${{ env.aws_new_ami_vpc_id }}\""
+                | jq -c ".builders[0].source_ami = \"${{ env.aws_source_ami_id }}\""
+                | jq -c ".builders[0].ami_regions = ${{ env.aws_additional_supported_regions }}"
+                > ami_config_tmp.json
+                && mv ami_config_tmp.json 
+                ami_config.json
+
+          # This spins up an AWS EC2 instance to create the AMI, and then deletes it
+          # It *could* fail if we are maxed-out in number AWS vCPUs allowed in aws_new_ami_source_region
+          - name: Create New AMI in aws_new_ami_source_region via Packer, Update Region, and Update Appropriate Database
+            working-directory: ecs-host-setup
+            run: |
+                # Log in as Admin to get Bearer Token for Update Region API call
+                token=$(curl -X POST \
+                  -H "Content-Type: application/json" \
+                  --data "{ \"username\": \"${{ secrets.HEROKU_ALL_WEBSERVERS_ADMIN_USERNAME }}\", \"password\": \"${{ secrets.HEROKU_ALL_WEBSERVERS_ADMIN_PASSWORD }}\" }" \
+                  "${{ env.webserver_url }}admin/login" | jq -r ".access_token")
+
+                # create the new AMI in aws_new_ami_source_region (region set in previous step) and copy to supported regions
+                packer -machine-readable build ami_config.json
+
+                # if packer fails, manifest.json does not get created and the entire workflow fails here
+                new_ami_ids=$(cat manifest.json | jq ".builds[0].artifact_id")
+
+                # loop through each region, replace comma with space for delimiting
+                for artifact in ${new_ami_ids//,/ }
+                do
+                  ami_id=$(echo ${artifact} | grep -oE 'ami-[0-9a-z]+')
+                  region=$(echo ${artifact} | grep -oE '[0-9a-z-]+:'| sed 's/.$//')
+
+                  # update appropriate database with new AMI IDs
+                  curl -X POST \
+                  -H "Content-Type: application/json" \
+                  -H "X-Hasura-Admin-Secret: ${{ env.hasura_graphql_access_key }}" \
+                  --data "{ \"query\": \"mutation { update_hardware_region_to_ami(_set: { ami_id: \\\"${ami_id}\\\" }, where: { region_name: { _eq: \\\"${region}\\\" } }) { returning { ami_id } } }\" }" \
+                  ${{ env.graphql_db_url }}
+
+                  # run update_region on each region
+                  celery_task_output_id=$(curl -X POST \
+                    -H "Content-Type: application/json" \
+                    -H "Authorization: Bearer ${token}" \
+                    --data "{\"region_name\": \"${region}\"}" \
+                    "${{ env.webserver_url }}aws_container/update_region" | jq -er ".ID") # the -e option makes jq return with error code 1 if element not found
+
+                  # ensures update_region was called successfully
+                  if [[ $? =~ 1 ]]; then
+                    echo "Failed to update $region" && false
+                  fi
+
+                  # poll for update_region and its subtasks 
+                  bash poll_task.sh ${{ env.webserver_url}} ${celery_task_output_id}
+                  if [[ $? =~ 1 ]]; then
+                    echo "Failed to update $region" && false
+                  fi
+
+                done
+
+    # AMI: Notify Slack
+    # Notify Slack after building and deploying the Fractal AMI to all supported AWS regions.
+    # Runs if ami-publish-ec2 succeeds.
+    ami-notify-slack:
+        name: "AMI: Notify Slack"
+        needs: [ami-publish-ec2]
         if: >
-            contains(fromJSON('["master"]'), needs.fractal-publish-build-config.outputs.branch) &&
-            contains(fromJSON('["all", "ecs-host-service-publish-build-s3"]'), needs.fractal-publish-build-config.outputs.job)
-        env:
-            binary-location: ecs-host-service/build
-            binary-name: ecs-host-service
-            s3-bucket-region: us-east-1
-            s3-bucket-uri: s3://fractal-ecs-host-service
-
+            success() &&
+            contains(fromJSON('["all", "ami-publish-ec2"]'), needs.fractal-publish-build-config.outputs.job)
+        runs-on: ubuntu-20.04
         steps:
-            - name: Checkout Git Repository
-              uses: actions/checkout@v2
-
-            - name: Setup Go environment
-              uses: actions/setup-go@v2.1.3
-
-            - name: Configure AWS CLI
-              uses: aws-actions/configure-aws-credentials@v1
-              with:
-                  aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
-                  aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
-                  aws-region: ${{ env.s3-bucket-region }}
-
-            - name: Install Go dependencies
-              working-directory: ecs-host-service
-              run: make deps
-
-            - name: Build Go project
-              env:
-                  WEBSERVER_AUTH_SECRET_DEV: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_DEV }}
-                  WEBSERVER_AUTH_SECRET_STAGING: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_STAGING }}
-                  WEBSERVER_AUTH_SECRET_PROD: ${{ secrets.HOST_SERVICE_AND_WEBSERVER_AUTH_SECRET_PROD }}
-              working-directory: ecs-host-service
-              run: make build
-
-            - name: Upload binary to S3
-              if: contains(fromJSON('["true"]'), needs.fractal-publish-build-config.outputs.publish)
-              run: aws s3 cp ${{ env.binary-location }}/${{ env.binary-name }} ${{ env.s3-bucket-uri }}/${{ env.binary-name }}
-
             - name: Notify Slack
               if: contains(fromJSON('["true"]'), needs.fractal-publish-build-config.outputs.publish)
               run: |
                   curl -X POST \
-                  --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Fractal Bot\", \"text\": \":athletic_shoe: ECS Host Service build pushed to production via S3 upload :bezos:\", \"icon_emoji\": \":fractal:\"}" \
+                  --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Fractal Bot\", \"text\": \"New Fractal AMI \`${{ needs.fractal-publish-build-config.outputs.branch }}\` Deployed to All Supported AWS Regions.\", \"icon_emoji\": \":fractal:\"}" \
                   ${{ secrets.SLACK_HOOKS_ENDPOINT }}
 
     # Main Webserver: Deploy to Heroku
