linux pipeline

diff --git a/.github/workflows/whist-build-and-deploy.yml b/.github/workflows/whist-build-and-deploy.yml
--- a/.github/workflows/whist-build-and-deploy.yml
+++ b/.github/workflows/whist-build-and-deploy.yml
@@ -14,6 +14,7 @@ on:
     branches:
       - prod
       - staging
+      - phil/linux-pipeline # TESTING TODO: remove this line
     paths-ignore:
       - "README.md"
       - "**/README.md"
@@ -98,20 +99,20 @@ jobs:
       - name: Detect Whether to Publish the Job(s) or Not
         id: detect-publish
         run: |
-          trap 'echo "::error::Command '\''$BASH_COMMAND'\'' exited with code $?"' ERR
-
-          ref="${{ github.ref }}"
-          target="${{ steps.set-deploy-environment.outputs.environment }}"
-
-          case "$ref" in
-            *prod|*staging|*dev)
-              # Get the short branch name for dev, staging, and
-              # prod by stripping away any leading characters. For
-              # example, "/refs/heads/dev" becomes "dev".
-              branch="${ref##*/}" ;;
-            *)
-                branch="$ref" ;;
-          esac
+          # TESTING TODO: remove this line
+          branch="dev"
+          # trap 'echo "::error::Command '\''$BASH_COMMAND'\'' exited with code $?"' ERR
+          # ref="${{ github.ref }}"
+          # target="${{ steps.set-deploy-environment.outputs.environment }}"
+          # case "$ref" in
+          #   *prod|*staging|*dev)
+          #     # Get the short branch name for dev, staging, and
+          #     # prod by stripping away any leading characters. For
+          #     # example, "/refs/heads/dev" becomes "dev".
+          #     branch="${ref##*/}" ;;
+          #   *)
+          #       branch="$ref" ;;
+          # esac
 
           # We are only allowed to deploy a branch to its corresponding
           # target deployment environment. In other words, we can only
@@ -170,6 +171,9 @@ jobs:
     runs-on: ubuntu-20.04
     concurrency: auth0-deploy-rules-${{ github.ref }}
     needs: [whist-publish-build-config]
+
+    # TESTING TODO: remove this line
+    if: false
 
     steps:
       - name: Checkout Git Repository
@@ -244,6 +248,9 @@ jobs:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_GITHUB_ACTIONS_USER_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_GITHUB_ACTIONS_USER_SECRET_ACCESS_KEY }}
 
+    # TESTING TODO: remove this line
+    if: false
+
     steps:
       - name: Checkout Git Repository
         uses: actions/checkout@v3
@@ -315,6 +322,10 @@ jobs:
     needs: [whist-publish-build-config]
     concurrency: mandelboxes-publish-ghcr-${{ github.ref }}
     uses: ./.github/workflows/mandelboxes-publish-ghcr.yml
+
+    # TESTING TODO: remove this line
+    if: false
+
     with:
       branch: ${{ needs.whist-publish-build-config.outputs.branch }}
       publish: ${{ needs.whist-publish-build-config.outputs.publish == 'true' }}
@@ -343,6 +354,9 @@ jobs:
     needs: [whist-publish-build-config, terraform-deploy]
     outputs:
       region_to_ami_map: ${{ steps.build-new-amis.outputs.region_to_ami_map }}
+
+    # TESTING TODO: remove this line
+    if: false
 
     steps:
       - name: Checkout Git Repository
@@ -599,12 +613,14 @@ jobs:
       new_dev_rc_version: ${{ steps.generate-release-version.outputs.new_dev_rc_version }}
 
     # Only run whist-browser deployment if none of the previous steps failed
-    if: |
-      always() &&
-      (needs.scaling-service-deploy.result == 'success') &&
-      (needs.auth0-deploy-rules.result == 'success') &&
-      (needs.mandelboxes-publish-ghcr.result == 'success') &&
-      (needs.amis-publish-aws.result == 'success')
+    # TESTING TODO: remove this line
+    # if: |
+    #   always() &&
+    #   (needs.scaling-service-deploy.result == 'success') &&
+    #   (needs.auth0-deploy-rules.result == 'success') &&
+    #   (needs.mandelboxes-publish-ghcr.result == 'success') &&
+    #   (needs.amis-publish-aws.result == 'success')
+    if: always()
 
     steps:
       - name: Checkout Git Repository
@@ -710,7 +726,7 @@ jobs:
   # Whist Browser: Build and Publish to AWS S3
   # Build the Whist Browser for all supported OSes
   whist-browser-publish-build-s3:
-    name: "Whist Browser: Build & Deploy Whist Browser (${{ matrix.config.target_os }} - ${{ matrix.config.target_arch }})"
+    name: "Whist Browser: Build & Deploy Whist Browser (${{ matrix.config.display_os }} - ${{ matrix.config.target_arch }})"
     runs-on: ${{ matrix.config.runner }}
     concurrency: whist-browser-publish-build-s3-${{ matrix.config.target_arch }}-${{ matrix.config.target_os }}-${{ github.ref }}
     needs:
@@ -721,28 +737,37 @@ jobs:
       ]
 
     # Only run whist-browser deployment if none of the previous steps failed
-    if: always() && (needs.whist-browser-retrieve-version-number.result == 'success')
+    # TESTING TODO: remove this line
+    # if: always() && (needs.whist-browser-retrieve-version-number.result == 'success')
+    if: always()
 
     strategy:
       matrix:
         config:
           - target_arch: "x64"
-            target_os: "macOS"
+            display_os: "macOS"
+            target_os: "macos"
             runner: [self-hosted, macOS, ARM64]
           - target_arch: "arm64"
-            target_os: "macOS"
+            display_os: "macOS"
+            target_os: "macos"
             runner: [self-hosted, macOS, ARM64]
+          - target_arch: "x64"
+            display_os: "Linux Ubuntu"
+            target_os: "linux"
+            runner: [self-hosted, Linux, x64]
 
     env:
-      macos-binary-tar-name: whist-browser-macos-${{ matrix.config.target_arch }}-${{ needs.whist-publish-build-config.outputs.branch }}.tar.gz
-      macos-s3-bucket-uri: s3://whist-browser-macos-${{ matrix.config.target_arch }}-${{ needs.whist-publish-build-config.outputs.branch }}
+      binary-tar-name: whist-browser-${{ matrix.config.target_os }}-${{ matrix.config.target_arch }}-${{ needs.whist-publish-build-config.outputs.branch }}.tar.gz
+      s3-bucket-uri: s3://whist-browser-${{ matrix.config.target_os }}-${{ matrix.config.target_arch }}-${{ needs.whist-publish-build-config.outputs.branch }}
       s3-bucket-region: us-east-1
 
     steps:
       ############################## Common Configuration Steps START #############################
 
-      # This helps fix an issue with GitHub Actions not finding the right keychain on the self-hosted runner
+      # This helps fix an issue with GitHub Actions not finding the right keychain on macOS self-hosted runners
       - name: Configure keychain
+        if: runner.os == 'macOS'
         run: git config --global credential.helper osxkeychain
 
       - name: Authenticate with GitHub (for pulling the required repositories automatically from the build scripts)
@@ -752,7 +777,6 @@ jobs:
         run: git config --global url.https://$GH_USERNAME:$GH_PAT@github.com/.insteadOf https://github.com/
 
       - name: Manually Git Clone `brave-browser`
-        if: runner.os == 'macOS'
         run: |
           # Since this is a self-hosted runner, we check if the `brave-browser` repo exists locally,
           # and if so we pull the latest changes. If it doesn't exist, we clone it.
@@ -814,7 +838,7 @@ jobs:
         uses: ilammy/msvc-dev-cmd@v1
 
       #############################################################################################
-      ############################### Unix Configuration Steps START ##############################
+      ############################### macOS Configuration Steps START #############################
 
       # Since we're using a self-hosted runner, we need to comment this out once it has run once
       # because the keychain will then exist and trying to reinstall it will fail. If you are
@@ -834,33 +858,60 @@ jobs:
           aws s3 cp s3://whist-dev-secrets/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8 ~/private_keys
 
       #############################################################################################
+      ############################### Linux Configuration Steps START #############################
+
+      # The Linux runner for building Chromium Whist needs to first be configured manually with some other packages. I am
+      # writing them here for reference, in case we need to create a new self-hosted runner
+      #    sudo apt-get install build-essential python-setuptools python3-distutils pkg-config gperf git gh libxdamage1 libgbm1 libatk1.0-0 awscli libdbus-1-dev
+      #    sudo apt-get install libasound2-dev libcurl4-openssl-dev libatk-bridge2.0-0 libxkbcommon-x11-0 libpango-1.0-0 nvidia-cuda-toolkit awscli
+      #    sudo snap install cmake --classic
+      # 
+      # Also, the AWS CLI needs to be configured with `aws configure` 
+
+      # See: https://github.com/brave/brave-browser/wiki/Linux-Development-Environment
+      - name: Install Linux Ubuntu Brave Browser Dependencies
+        if: runner.os == 'Linux'
+        working-directory: brave-browser
+        run: ./src/build/install-build-deps.sh --no-prompt --no-nacl --no-chromeos-fonts --no-arm
+
+      #############################################################################################
       ##################################### Build Steps START #####################################
 
       # Building Brave/Chromium requires specific Node & npm versions, and Xcode. For full
       # details, see: https://github.com/whisthq/brave-browser#readme
       # These are fine to set globally even if the self-hosted runner is used by a Whist engineer
       # since the Node, NPM, and Xcode versions should match for development and deploys.
-      - name: Log NodeJS, NPM and Xcode Versions
+      - name: Log NodeJS, NPM and Xcode (on macOS only) Versions
         run: |
-          # Necessary to use nvm from bash on macOS
+          # Necessary to use nvm from bash on macOS (needs nvm to be installed already)
           source ~/.nvm/nvm.sh
 
-          echo "Force NodeJS version 16 and NPM version 8.5.0..."
-          npm install -g npm@8.5.0
+          echo "Force NodeJS version 16 and NPM version 8.5.5..."
+          nvm install 16
           nvm use 16
+          npm install -g npm@8.5.5
 
           echo ""
-          echo "Verifying NodeJS & NPM versions (Need 16.x and 8.5.0)..."
-          node --version
-          npm --version
+          echo "Verifying NodeJS & NPM versions (Need 16.x and 8.5.5)..."
+          echo -n "NodeJS version: " && node --version
+          echo -n "NPM version: " && npm --version
 
-          echo ""
-          echo "Verifying that Xcode is installed and up-to-date (Need 13.x)..."
-          xcodebuild -version
+          if [[ "${{ runner.os }}" == "macOS" ]]; then
+            echo ""
+            echo "Verifying that Xcode is installed and up-to-date (Need 13.x)..."
+            xcodebuild -version
+          fi
 
       - name: Initialize the Build Environment
         working-directory: brave-browser
-        run: npm install
+        run: |
+          # nvm doesn't scope well across GitHub Actions steps on Linux, so we forcefully make sure that it is using
+          # the proper versions of NodeJS & NPM
+          source ~/.nvm/nvm.sh
+          nvm use 16 && echo -n "NPM version: " && npm --version
+
+          # Install dependencies
+          npm install
 
       - name: Configure Build Type
         working-directory: brave-browser
@@ -873,17 +924,44 @@ jobs:
             # Production build, set official build as true and build Chromium as Release
             export npm_config_is_official_build=true
             echo "build_type=Release" >> $GITHUB_ENV
-            echo "executable_name=Whist Browser" >> $GITHUB_ENV
+
+            if [[ "${{ runner.os }}" == "macOS" ]]; then
+              echo "executable_name=Whist Browser.app" >> $GITHUB_ENV
+            elif [[ "${{ runner.os }}" == "Linux" ]]; then
+              # TODO: We need to rename this to something like `whist-browser`
+              echo "executable_name=brave" >> $GITHUB_ENV
+            else
+              echo "Unsupported OS for setting Whist Browser executable name!"
+              exit 1
+            fi
           elif [[ "${{ needs.whist-publish-build-config.outputs.branch }}" == "staging" ]]; then
             # Staging build, set official build as false and build Chromium as Release
             export npm_config_is_official_build=false
             echo "build_type=Release" >> $GITHUB_ENV
-            echo "executable_name=Whist Browser" >> $GITHUB_ENV
+
+            if [[ "${{ runner.os }}" == "macOS" ]]; then
+              echo "executable_name=Whist Browser.app" >> $GITHUB_ENV
+            elif [[ "${{ runner.os }}" == "Linux" ]]; then
+              # TODO: We need to rename this to something like `whist-browser`
+              echo "executable_name=brave" >> $GITHUB_ENV
+            else
+              echo "Unsupported OS for setting Whist Browser executable name!"
+              exit 1
+            fi
           else
             # Dev build, set official build as false and build Chromium as Debug
             export npm_config_is_official_build=false
             echo "build_type=Debug" >> $GITHUB_ENV
-            echo "executable_name=Whist Browser Development" >> $GITHUB_ENV
+
+            if [[ "${{ runner.os }}" == "macOS" ]]; then
+              echo "executable_name=Whist Browser Development.app" >> $GITHUB_ENV
+            elif [[ "${{ runner.os }}" == "Linux" ]]; then
+              # TODO: We need to rename this to something like `whist-browser`
+              echo "executable_name=brave" >> $GITHUB_ENV
+            else
+              echo "Unsupported OS for setting Whist Browser executable name!"
+              exit 1
+            fi
           fi
 
       # We need to configure build parameters, to build for the proper architecture and with
@@ -957,11 +1035,23 @@ jobs:
 
       - name: Fetch Chromium Source & Dependencies
         working-directory: brave-browser
-        run: npm run init
+        run: |
+          # nvm doesn't scope well across GitHub Actions steps on Linux, so we forcefully make sure that it is using
+          # the proper versions of NodeJS & NPM
+          source ~/.nvm/nvm.sh
+          nvm use 16 && echo -n "NPM version: " && npm --version
+
+          # Download and prepare Chromium/Brave for building
+          npm run init
 
       - name: Build Whist Browser
         working-directory: brave-browser
         run: |
+          # nvm doesn't scope well across GitHub Actions steps on Linux, so we forcefully make sure that it is using
+          # the proper versions of NodeJS & NPM
+          source ~/.nvm/nvm.sh
+          nvm use 16 && echo -n "NPM version: " && npm --version
+
           # Set the environment variables for the Whist Extension
           # Note that these values are public, so it's fine to hardcode them here (rather than using GitHub Secrets)
           if [[ "${{ needs.whist-publish-build-config.outputs.branch }}" == "prod" ]]; then
@@ -992,7 +1082,7 @@ jobs:
       # Note: Sentry makes use of sudo. To make it work on a self-hosted macOS runner, follow:
       # https://apple.stackexchange.com/questions/257813/enable-sudo-without-a-password-on-macos
       - name: Copy Client debug symbols to Sentry, on macOS
-        if: runner.os == 'macOS'
+        if: runner.os == 'macOS' || runner.os == 'Linux'
         working-directory: brave-browser/src/brave/whist
         env:
           SENTRY_ORG: whist
@@ -1002,8 +1092,16 @@ jobs:
           # Uncomment this line to install sentry-cli. Since we're running on a self-hosted runner, we
           # comment it out after having run it once
           # curl -sL https://sentry.io/get-cli/ | bash
-          sentry-cli upload-dif protocol/build-lib/client/build64/libWhistClient.dylib
-          sentry-cli upload-dif protocol/build-lib/client/build64/WhistClient.debug
+          if [[ "${{ runner.os }}" == "macOS" ]]; then
+            sentry-cli upload-dif protocol/build-lib/client/build64/libWhistClient.dylib
+            sentry-cli upload-dif protocol/build-lib/client/build64/WhistClient.debug
+          elif [[ "${{ runner.os }}" == "Linux" ]]; then
+            sentry-cli upload-dif protocol/build-lib/client/build64/libWhistClient.so
+            sentry-cli upload-dif protocol/build-lib/client/build64/WhistClient.debug
+          else
+            echo "Unsupported OS for uploading Sentry debug symbols!"
+            exit 1
+          fi
 
       - name: Tar & Upload Whist Browser to AWS S3
         working-directory: brave-browser/src/out
@@ -1014,8 +1112,8 @@ jobs:
           else
             BUILD_OUTPUT_FOLDER="${{ env.build_type }}_${{ matrix.config.target_arch }}"
           fi
-          tar -zcvf "${{ env.macos-binary-tar-name }}" "$BUILD_OUTPUT_FOLDER/${{ env.executable_name }}.app"
-          aws s3 cp "${{ env.macos-binary-tar-name }}" "${{ env.macos-s3-bucket-uri }}/${{ env.macos-binary-tar-name }}"
+          tar -zcvf "${{ env.binary-tar-name }}" "$BUILD_OUTPUT_FOLDER/${{ env.executable_name }}"
+          aws s3 cp "${{ env.binary-tar-name }}" "${{ env.s3-bucket-uri }}/${{ env.binary-tar-name }}"
 
       ###################################################################################
 
